runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:

# - url: /bootstrap
#   static_dir: bootstrap
- url: /api/(.*)
  script: main.app

- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
# - url: /.*
#   script: main.app

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]

# runtime: python27
# api_version: 1
# threadsafe: true
#
# handlers:
# - url: /
#   static_files: www/index.html
#   upload: www/index.html
#
# - url: /(.*)
#   static_files: www/\1
#   upload: www/(.*)
